name: test-python-snap
base: core18
version: '0.1dev'
summary: Python Test Snap
description: |
    This is test snap for python applications.
grade: devel
confinement: strict
architectures: 
  - build-on: amd64 
    run-on: armhf

parts:
  test-python-snap:
    source: .
    plugin: python
    python-version: python3
    requirements: ['requirements.txt']
apps:
  test-python-snap:
    command: test-python-snap
    plugs: [home, network, network-bind, mount-observe]